################################################################################
# GENERAL SETTINGS                                                             #
################################################################################

# sets TTY for `gpg-agent`
ttyname $GPG_TTY

# disables pin entry cache
default-cache-ttl 600 # 10 minutes
max-cache-ttl 7200 # 2 hours
